
spring:
  server:
    error:
      include-exception: true
      include-message: ALWAYS
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: "spring_boot_test"
      auto-index-creation: true
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: "no-reply@qwe.rty"
      text: "no-reply"
jwt:
  secret: ${JWT_SECRET}